export const SET_LOADING = 'SET_LOADING'

export const SET_KOI = 'SET_KOI'

export const SET_ERROR = 'SET_ERROR'

export const CLEAR_ERROR = 'CLEAR_ERROR'

export const SET_CREATE_WALLET = 'SET_CREATE_WALLET'

export const SET_ASSETS = 'SET_ASSETS'

export const SET_ACTIVITIES = 'SET_ACTIVITIES'

export const SET_CONT_LOADING = 'SET_CONT_LOADING'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'

export const SET_WARNING = 'SET_WARNING'

export const CLEAR_WARNING = 'CLEAR_WARNING'

export const CLEAR_ACTIVITIES = 'CLEAR_ACTIVITIES'

export const SET_ACCOUNT_NAME = 'SET_ACCOUNT_NAME'

export const SET_PRICE = 'SET_PRICE'

export const SET_CURRENCY = 'SET_CURRENCY'

export const SET_ACCOUNTS = 'SET_ACCOUNTS'

// Default account
export const SET_DEFAULT_ARWEAVE_ACCOUNT = 'SET_DEFAULT_ARWEAVE_ACCOUNT'
export const SET_DEFAULT_K2_ACCOUNT = 'SET_DEFAULT_K2_ACCOUNT'

// Default Ethereum account
export const SET_DEFAULT_ETHEREUM_ACCOUNT = 'SET_DEFAULT_ETHEREUM_ACCOUNT'

export const SET_DEFAULT_SOLANA_ACCOUNT = 'SET_DEFAULT_SOLANA_ACCOUNT'

export const SET_ACTIVITY_NOTIFICATIONS = 'SET_ACTIVITY_NOTIFICATIONS'

export const SET_SETTINGS = 'SET_SETTINGS'

export const SET_ASSETS_TAB_SETTINGS = 'SET_ASSETS_TAB_SETTINGS'

export const SET_ACTIVATED_CHAIN = 'SET_ACTIVATED_CHAIN'
