export const SET_LOADING = 'SET_LOADING'

export const SET_KOI = 'SET_KOI'

export const SET_ERROR = 'SET_ERROR'

export const SET_CREATE_WALLET = 'SET_CREATE_WALLET'

export const SET_ASSETS = 'SET_ASSETS'

export const SET_ACTIVITIES = 'SET_ACTIVITIES'

export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'

export const SET_CONT_LOADING = 'SET_CONT_LOADING'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const SET_CURSOR = 'SET_OWNED_CURSOR'

export const CLEAR_ACTIVITIES = 'CLEAR_ACTIVITIES'
