// Accounts
export const ADD_ACCOUNT_BY_ADDRESS = 'ADD_ACCOUNT_BY_ADDRESS'
export const SET_ACCOUNTS = 'SET_ACCOUNTS'

// Default account
export const SET_DEFAULT_ACCOUNT = 'SET_DEFAULT_ACCOUNT'
export const SET_DEFAULT_ACCOUNT_BY_ADDRESS = 'SET_DEFAULT_ACCOUNT_BY_ADDRESS'
export const UPDATE_DEFAULT_ACCOUNT = 'UPDATE_DEFAULT_ACCOUNT'

// Create collections
export const SET_CREATE_COLLECTION = 'SET_CREATE_COLLECTION'

// Collections
export const SET_COLLECTIONS = 'SET_COLLECTIONS'
export const SET_FILTER_COLLECTIONS = 'SET_FILTER_COLLECTIONS'

// Assets (NFT)
export const SET_ASSETS = 'SET_ASSETS'
export const SET_FILTER_NFTS = 'SET_FILTER_NFTS'
export const SET_COLLECTION_NFTS = 'SET_COLLECTION_NFTS'
