// Accounts
export const ADD_ACCOUNT_BY_ADDRESS = 'ADD_ACCOUNT_BY_ADDRESS'
export const SET_ACCOUNTS = 'SET_ACCOUNTS'

// Address Book
export const SHOW_ADDRESS_BOOK = 'SHOW_ADDRESS_BOOK'
export const HIDE_ADDRESS_BOOK = 'HIDE_ADDRESS_BOOK'

// Default account
export const SET_DEFAULT_ACCOUNT = 'SET_DEFAULT_ACCOUNT'
export const SET_DEFAULT_ACCOUNT_BY_ADDRESS = 'SET_DEFAULT_ACCOUNT_BY_ADDRESS'
export const UPDATE_DEFAULT_ACCOUNT = 'UPDATE_DEFAULT_ACCOUNT'

// Create collections
export const SET_CREATE_COLLECTION = 'SET_CREATE_COLLECTION'

// Collections
export const SET_COLLECTIONS = 'SET_COLLECTIONS'
export const SET_FILTER_COLLECTIONS = 'SET_FILTER_COLLECTIONS'

// Assets (NFT)
export const SET_ASSETS = 'SET_ASSETS'
export const SET_FILTER_NFTS = 'SET_FILTER_NFTS'
export const SET_COLLECTION_NFTS = 'SET_COLLECTION_NFTS'

// Notifications
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS'
