// Accounts
export const ADD_ACCOUNT_BY_ADDRESS = 'ADD_ACCOUNT_BY_ADDRESS'
export const SET_ACCOUNTS = 'SET_ACCOUNTS'

// Address Book
export const SHOW_ADDRESS_BOOK = 'SHOW_ADDRESS_BOOK'
export const HIDE_ADDRESS_BOOK = 'HIDE_ADDRESS_BOOK'

// Default accounts
export const SET_DEFAULT_ARWEAVE_ACCOUNT = 'SET_DEFAULT_ARWEAVE_ACCOUNT'
export const SET_DEFAULT_ETHEREUM_ACCOUNT = 'SET_DEFAULT_ETHEREUM_ACCOUNT'
export const SET_DEFAULT_SOLANA_ACCOUNT = 'SET_DEFAULT_SOLANA_ACCOUNT'
export const SET_DEFAULT_K2_ACCOUNT = 'SET_DEFAULT_K2_ACCOUNT'

// Create collections
export const SET_CREATE_COLLECTION = 'SET_CREATE_COLLECTION'

// Collections
export const SET_COLLECTIONS = 'SET_COLLECTIONS'
export const SET_FILTER_COLLECTIONS = 'SET_FILTER_COLLECTIONS'

// Assets (NFT)
export const SET_ASSETS = 'SET_ASSETS'
export const SET_FILTER_NFTS = 'SET_FILTER_NFTS'
export const SET_COLLECTION_NFTS = 'SET_COLLECTION_NFTS'

// Notifications
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS'

// Loading
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const SET_LOADED = 'SET_LOADED'

// Onboarding Processing
export const SET_IS_ONBOARDING = 'SET_IS_ONBOARDING'
export const SET_ONBOARDING_PROCESSING = 'SET_ONBOARDING_PROCESSING'
export const SET_ONBOARDING_PROCESSED = 'SET_ONBOARDING_PROCESSED'

// Error
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Quick Notification
export const SET_QUICK_NOTIFICATION = 'SET_QUICK_NOTIFICATION'
export const CLEAR_QUICK_NOTIFICATION = 'CLEAR_QUICK_NOTIFICATION'
