version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          name: Save Cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: yarn test
      - run: yarn coveralls

workflows:
  version: 2
  test-only:
    jobs:
      - build_and_test
