export const ACCOUNT = {
  ADDRESS: 'ADDRESS',
  KEY: 'KEY',
  SEED_PHRASE: 'SEED_PHRASE',
  BAlANCE: 'BALANCE',
  ASSETS: 'ASSETS',
  ACTIVITIES: 'ACTIVITIES',
  PRICE: 'PRICE',
  PENDING_TRANSACTION: 'PENDING_TRANSACTION',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  COLLECTIONS: 'COLLECTION',
  KOI_BALANCE: 'KOI_BALANCE',
  TYPE: 'TYPE',
  ENCRYPTED_KEY: 'ENCRYPTED_KEY',
  PENDING_CONFIRMATION_TRANSACTION: 'PENDING_CONFIRMATION_TRANSACTION',
  CONNECTED_SITE: 'CONNECTED_SITE',
  PROVIDER: 'PROVIDER'
}

export const ADDRESSES = {
  ETHEREUM: 'ETHEREUM_ADDRESSES',
  ARWEAVE: 'ARWEAVE_ADDRESSES'
}

export const TYPE = {
  ARWEAVE: 'TYPE_ARWEAVE',
  ETHEREUM: 'TYPE_ETHEREUM'
}

export const IMPORTED = {
  ARWEAVE: 'IMPORTED_ARWEAVE',
  ETHEREUM: 'IMPORTED_ETHEREUM'
}
