export const ACCOUNT = {
  ADDRESS: 'ADDRESS',
  KEY: 'KEY',
  SEED_PHRASE: 'SEED_PHRASE',
  BAlANCE: 'BALANCE',
  ASSETS: 'ASSETS',
  ACTIVITIES: 'ACTIVITIES',
  PRICE: 'PRICE',
  PENDING_TRANSACTION: 'PENDING_TRANSACTION',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  COLLECTIONS: 'COLLECTION',
  KOI_BALANCE: 'KOI_BALANCE',
  TYPE: 'TYPE',
  ENCRYPTED_KEY: 'ENCRYPTED_KEY',
  PENDING_CONFIRMATION_TRANSACTION: 'PENDING_CONFIRMATION_TRANSACTION',
  CONNECTED_SITE: 'CONNECTED_SITE',
  PROVIDER: 'PROVIDER',
  AFFILIATE_CODE: 'AFFILIATE_CODE',
  INVITE_SPENT: 'INVITE_SPENT',
  TOTAL_REWARD: 'TOTAL_REWARD',
  DID_DATA: 'DID_DATA'
}

export const ADDRESSES = {
  ETHEREUM: 'ETHEREUM_ADDRESSES',
  ARWEAVE: 'ARWEAVE_ADDRESSES'
}

export const TYPE = {
  ARWEAVE: 'TYPE_ARWEAVE',
  ETHEREUM: 'TYPE_ETHEREUM',
  SOLANA: 'TYPE_SOLANA',
  K2: 'K2'
}

export const IMPORTED = {
  ARWEAVE: 'IMPORTED_ARWEAVE',
  ETHEREUM: 'IMPORTED_ETHEREUM',
  SOLANA: 'IMPORTED_SOLANA',
  K2: 'K2'
}
