export const NETWORK = {
  ARWEAVE: 'ARWEAVE',
  ETHEREUM: 'ETHEREUM'
}

export const WALLET = {
  ADDRESS: 'ADDRESS',
  KEY: 'KEY',
  SEED_PHRASE: 'SEED_PHRASE',
  BALANCE: 'BALACNE',
  ASSETS: 'ASSETS',
  ACTIVITIES: 'ACTIVITIES',
  PRICE: 'PRICE',
  PENDING_TRANSACTIONS: 'PENDING_TRANSACTIONS',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  COLLECTIONS: 'COLLECTIONS'
}

export const GENERIC = {
  SHOW_WELCOME_SCREEN : 'SHOW_WELCOME_SCREEN',
  PENDING_REQUEST: 'PENDING_REQUEST',
  KOI_BALANCE: 'KOI_BALANCE',
  SELECTED_CURRENCY: 'SELECTED_CURRENCY',
  CONNECTED_SITE: 'CONNECTED_SITE',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  AFFILIATE_CODE: 'AFFILIATE_CODE',
  UNLOCKED: 'UNLOCKED',
  NFT_BIT_DATA: 'NFT_BIT_DATA',
  ACTIVITY_NOTIFICATIONS: 'ACTIVITY_NOTIFICATIONS',
  TOKEN_PRICE: 'TOKEN_PRICE',
  TRANSACTION_DATA: 'TRANSACTION_DATA',
  SAVED_NFT_FORM: 'SAVED_NFT_FORM',
  ADDRESS_BOOK: 'ADDRESS_BOOK'
}

export const SETTING = {
  SELECTED_CURRENCY: 'SELECTED_CURRENCY',
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
  SHOW_VIEWS: 'SHOW_VIEWS',
  SHOW_EARNED_KOI: 'SHOW_EARNED_KOI',
  SHOW_ACTIVITIES_BY: 'SHOW_ACTIVITIES_BY',
  ACTIVATED_ACCOUNT: 'ACTIVATED_ACCOUNT',
  CONNECT_SITE_ACCOUNT: 'CONNECT_SITE_ACCOUNT',
  SITE_ADDRESS_DICTIONARY: 'SITE_ADDRESS_DICTIONARY',
  ASSETS_TAB_SETTINGS: 'ASSETS_TAB_SETTINGS'
}

export const SHOW_ACTIVITIES_BY = {
  ALL_ACCOUNTS: 'ALL_ACCOUNTS',
  INDIVIDUAL: 'INDIVIDUAL'
}
