export const NETWORK = {
  ARWEAVE: 'ARWEAVE',
  ETHEREUM: 'ETHEREUM'
}

export const WALLET = {
  ADDRESS: 'ADDRESS',
  KEY: 'KEY',
  SEED_PHRASE: 'SEED_PHRASE',
  BALANCE: 'BALACNE',
  ASSETS: 'ASSETS',
  ACTIVITIES: 'ACTIVITIES',
  PRICE: 'PRICE',
  PENDING_TRANSACTIONS: 'PENDING_TRANSACTIONS',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  COLLECTIONS: 'COLLECTIONS'
}

export const GENERIC = {
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
  PENDING_REQUEST: 'PENDING_REQUEST',
  KOI_BALANCE: 'KOI_BALANCE',
  SELECTED_CURRENCY: 'SELECTED_CURRENCY',
  CONNECTED_SITE: 'CONNECTED_SITE',
  ACCOUNT_NAME: 'ACCOUNT_NAME',
  AFFILIATE_CODE: 'AFFILIATE_CODE',
  UNLOCKED: 'UNLOCKED',
  NFT_BIT_DATA: 'NFT_BIT_DATA',
  ACTIVITY_NOTIFICATIONS: 'ACTIVITY_NOTIFICATIONS',
  TOKEN_PRICE: 'TOKEN_PRICE',
  TRANSACTION_DATA: 'TRANSACTION_DATA',
  SAVED_NFT_FORM: 'SAVED_NFT_FORM',
  ADDRESS_BOOK: 'ADDRESS_BOOK',
  ALL_ACTIVITIES: 'ALL_ACTIVITIES',
  PUSH_NOTIFICATION: 'PUSH_NOTIFICATION'
}

export const SETTING = {
  SELECTED_CURRENCY: 'SELECTED_CURRENCY',
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
  SHOW_VIEWS: 'SHOW_VIEWS',
  SHOW_EARNED_KOI: 'SHOW_EARNED_KOI',
  SHOW_ACTIVITIES_BY: 'SHOW_ACTIVITIES_BY',
  ACTIVATED_ARWEAVE_ACCOUNT: 'ACTIVATED_ARWEAVE_ACCOUNT',
  ACTIVATED_ETHEREUM_ACCOUNT: 'ACTIVATED_ETHEREUM_ACCOUNT',
  ACTIVATED_SOLANA_ACCOUNT: 'ACTIVATED_SOLANA_ACCOUNT',
  ACTIVATED_K2_ACCOUNT: 'ACTIVATED_K2_ACCOUNT',
  CONNECT_SITE_ACCOUNT: 'CONNECT_SITE_ACCOUNT',
  SITE_ADDRESS_DICTIONARY: 'SITE_ADDRESS_DICTIONARY',
  ASSETS_TAB_SETTINGS: 'ASSETS_TAB_SETTINGS',
  DISABLED_ORIGINS: 'DISABLED_ORIGINS',
  SITE_CONNECTED_ADDRESSES: 'SITE_CONNECTED_ADDRESSES',
  ETHEREUM_PROVIDER: 'ETHEREUM_PROVIDER',
  SOLANA_PROVIDER: 'SOLANA_PROVIDER',
  K2_PROVIDER: 'K2_PROVIDER',
  ACTIVATED_CHAIN: 'ACTIVATED_CHAIN',
  IMPORTED_ERC20_TOKENS: 'IMPORTED_ERC20_TOKENS',
  IMPORTED_SOLANA_CUSTOM_TOKENS: 'IMPORTED_SOLANA_CUSTOM_TOKENS',
  IMPORTED_K2_CUSTOM_TOKENS: 'IMPORTED_K2_CUSTOM_TOKENS',
  OVERWRITE_ALTERNATIVES_SITES: 'OVERWRITE_ALTERNATIVES_SITES',
  CUSTOM_EVM_NETWORKS: 'CUSTOM_EVM_NETWORKS',
  CUSTOM_ARWEAVE_NETWORKS: 'CUSTOM_ARWEAVE_NETWORKS',
  CUSTOM_SOLANA_NETWORKS: 'CUSTOM_SOLANA_NETWORKS',
  CUSTOM_K2_NETWORKS: 'CUSTOM_K2_NETWORKS',
  ADDED_EVM_NETWORKS: 'ADDED_EVM_NETWORKS',
  DISPLYED_IMPORTED_TOKEN: 'DISPLYED_IMPORTED_TOKEN'
}

export const SHOW_ACTIVITIES_BY = {
  ALL_ACCOUNTS: 'ALL_ACCOUNTS',
  INDIVIDUAL: 'INDIVIDUAL'
}
