export const WALLET = {
  KOI_ADDRESS: 'KOI_ADDRESS',
  KOI_KEY: 'KOI_KEY',
  WALLET_NAMEL: 'WALLET_NAME',
  BALANCES: 'BALANCES',
  CONTENT_LIST: 'CONTENT_LIST',
  ACTIVITIES: 'ACTIVITIES'
}

export const NETWORK = {
  ARWEAVE: 'ARWEAVE',
  ETHEREUM: 'ETHEREUM'
}

export const GENERIC = {
  SHOW_WELCOME_SCREEN: 'SHOW_WELCOME_SCREEN',
  PENDING_REQUEST: 'PENDING_REQUEST',

}


export const REQUEST = {
  CONNECT_SITE: 'CONNECT_SITE',
  SIGN_TRANSACTION: 'SIGN_TRANSACTION'
}
