export const NETWORK = {
  ARWEAVE: 'ARWEAVE',
  ETHEREUM: 'ETHEREUM'
}

export const WALLET = {
  ADDRESS: 'ADDRESS',
  KEY: 'KEY',
  SEED_PHRASE: 'SEED_PHRASE',
  BALANCE: 'BALACNE',
  ASSETS: 'ASSETS',
  ACTIVITIES: 'ACTIVITIES',
  PRICE: 'PRICE',
  PENDING_TRANSACTIONS: 'PENDING_TRANSACTIONS'
}

export const GENERIC = {
  SHOW_WELCOME_SCREEN : 'SHOW_WELCOME_SCREEN',
  PENDING_REQUEST: 'PENDING_REQUEST',
  KOI_BALANCE: 'KOI_BALANCE',
  SELECTED_CURRENCY: 'SELECTED_CURRENCY',
  CONNECTED_SITE: 'CONNECTED_SITE',
  ACCOUNT_NAME: 'ACCOUNT_NAME'
}
