export const TRANSACTION_TYPE = {
  ORIGIN_TOKEN_TRANSFER: 'ORIGIN_TOKEN_TRANSFER',
  CUSTOM_TOKEN_TRANSFER: 'CUSTOM_TOKEN_TRANSFER',
  CONTRACT_DEPLOYMENT: 'CONTRACT_DEPLOYMENT',
  CONTRACT_INTERACTION: 'CONTRACT_INTERACTION'
}

export const TAB = {
  DETAIL: 'DETAIL',
  DATA: 'DATA'
}
