export const TRANSACTION_TYPE = {
  ORIGIN_TOKEN_TRANSFER: 'ORIGIN_TOKEN_TRANSFER',
  CUSTOM_TOKEN_TRANSFER: 'CUSTOM_TOKEN_TRANSFER',
  CONTRACT_DEPLOYMENT: 'CONTRACT_DEPLOYMENT',
  CONTRACT_INTERACTION: 'CONTRACT_INTERACTION'
}

export const TRANSACTION_METHOD = {
  SET_APPROVAL_FOR_ALL: 'SET_APPROVAL_FOR_ALL',
  MINT_COLLECTIBLES: 'MINT_COLLECTIBLES',
  APPROVE: 'APPROVE',
  CONTRACT_INTERACTION: 'CONTRACT_INTERACTION',
  CONTRACT_DEPLOYMENT: 'CONTRACT_DEPLOYMENT',
  TOKEN_TRANSFER: 'TOKEN_TRANSFER'
}

export const TAB = {
  DETAIL: 'DETAIL',
  DATA: 'DATA',
  SIMULATION: 'SIMULATION'
}
